// Video metadata export/ingest — turn what ecmanim already knows at render time
// (duration, dimensions, and the scene's section structure) into the web's video
// metadata standards, and read one of them back.
//
//   - schema.org VideoObject (JSON-LD)  -> discovery ("what is this video?")
//   - IIIF Presentation 3.0 Manifest    -> presentation/navigation ("how do I
//     view and move through it?"), with chapters derived from nextSection().
//   - a lightweight provenance sliver    -> "generated by ecmanim" + the IPTC
//     digital-source-type for programmatic/algorithmic media.
//
// This is EXPORT-first: adapters read from the scene / render result, they do not
// introduce a second normalized model. `resolveIIIFVideo()` is the one importer,
// used by VideoMobject's loadVideo() to ingest an IIIF-described clip.
//
// Isomorphic (no Node/DOM/`fetch` at module load). Pure data in, plain objects
// out — the caller decides how to serialize/embed them.

/** Version stamped into provenance. Kept in step with package.json on release. */
export const MANIM_JS_VERSION = "1.6.0";

// A section boundary (structurally identical to Scene's SceneSection) — used to
// derive chapters without importing the Scene module.
export interface MetaSection {
  name: string;
  startFrame: number;
  endFrame: number;
  type?: string;
  id?: number;
}

/** A chapter/segment on the timeline (seconds). */
export interface Chapter {
  label: string;
  start: number;
  end: number;
}

/** Provenance inputs (all optional). */
export interface ProvenanceInput {
  generator?: string;         // default "ecmanim"
  version?: string;           // default MANIM_JS_VERSION
  /**
   * IPTC "digital source type" controlled-vocabulary IRI. Programmatic renders
   * are algorithmic media; defaults to the algorithmicMedia term. Set to null to
   * omit, or to the trainedAlgorithmicMedia term for ML-generated content.
   */
  digitalSourceType?: string | null;
  sceneName?: string;
}

/** Everything the adapters can use. Supply what you have; unknowns are omitted. */
export interface VideoMetaInput {
  // Timing / geometry (from a render result). Duration is frames/fps if not given.
  durationSeconds?: number;
  frames?: number;
  fps?: number;
  width?: number;
  height?: number;
  // Identity / web fields.
  id?: string;                 // canonical IRI of the video/manifest
  contentUrl?: string;         // URL of the actual video file
  embedUrl?: string;
  name?: string;
  description?: string;
  language?: string;           // BCP-47 tag for IIIF language maps (default "none")
  thumbnailUrl?: string | string[];
  uploadDate?: string;         // ISO 8601 date/datetime
  encodingFormat?: string;     // MIME, e.g. "video/mp4"
  // Structure -> chapters.
  sections?: MetaSection[];
  chapters?: Chapter[];        // explicit chapters (win over `sections`)
  // Provenance. `true` = defaults; an object = customized; falsy = omitted.
  provenance?: ProvenanceInput | boolean;
}

// IPTC digital-source-type: media created by a purely algorithmic process.
export const IPTC_ALGORITHMIC_MEDIA =
  "http://cv.iptc.org/newscodes/digitalsourcetype/algorithmicMedia";

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

/** Duration in seconds, from an explicit value or frames/fps. */
export function metaDuration(input: VideoMetaInput): number {
  if (input.durationSeconds != null) return Math.max(0, input.durationSeconds);
  if (input.frames != null && input.fps) return Math.max(0, input.frames / input.fps);
  return 0;
}

/** Format seconds as an ISO-8601 duration, e.g. 90 -> "PT1M30S". */
export function toISODuration(seconds: number): string {
  const s0 = Math.max(0, seconds);
  const h = Math.floor(s0 / 3600);
  const m = Math.floor((s0 % 3600) / 60);
  const s = s0 - h * 3600 - m * 60;
  let out = "PT";
  if (h) out += `${h}H`;
  if (m) out += `${m}M`;
  if (s || (!h && !m)) {
    const sec = Number.isInteger(s) ? String(s) : s.toFixed(3).replace(/\.?0+$/, "");
    out += `${sec}S`;
  }
  return out;
}

// An IIIF language map ({ "<lang>": ["value"] }) for a single string.
function langMap(value: string | undefined, language?: string): any | undefined {
  if (value == null) return undefined;
  return { [language || "none"]: [String(value)] };
}

/** Chapters (seconds) from an input's explicit `chapters` or its `sections`. */
export function chaptersFrom(input: VideoMetaInput): Chapter[] {
  if (input.chapters && input.chapters.length) return input.chapters;
  const fps = input.fps || 0;
  if (!input.sections || !fps) return [];
  return input.sections.map((s) => ({
    label: s.name,
    start: s.startFrame / fps,
    end: s.endFrame / fps,
  }));
}

// Normalize the provenance input into a concrete descriptor (or null to omit).
function resolveProvenance(p: VideoMetaInput["provenance"]): Required<Omit<ProvenanceInput, "sceneName">> & { sceneName?: string } | null {
  if (!p) return null;
  const o: ProvenanceInput = p === true ? {} : p;
  return {
    generator: o.generator ?? "ecmanim",
    version: o.version ?? MANIM_JS_VERSION,
    digitalSourceType: o.digitalSourceType === undefined ? IPTC_ALGORITHMIC_MEDIA : o.digitalSourceType,
    sceneName: o.sceneName,
  };
}

// ---------------------------------------------------------------------------
// schema.org VideoObject (JSON-LD)
// ---------------------------------------------------------------------------

// Emit a schema.org VideoObject as a plain JSON-LD object (embed it in a page
// inside <script type="application/ld+json">). Only present fields are included.
export function toVideoObject(input: VideoMetaInput): Record<string, any> {
  const duration = metaDuration(input);
  const obj: Record<string, any> = {
    "@context": "https://schema.org",
    "@type": "VideoObject",
  };
  if (input.name != null) obj.name = input.name;
  if (input.description != null) obj.description = input.description;
  if (input.thumbnailUrl != null) obj.thumbnailUrl = input.thumbnailUrl;
  if (input.uploadDate != null) obj.uploadDate = input.uploadDate;
  if (duration > 0) obj.duration = toISODuration(duration);
  if (input.contentUrl != null) obj.contentUrl = input.contentUrl;
  if (input.embedUrl != null) obj.embedUrl = input.embedUrl;
  if (input.width != null) obj.width = input.width;
  if (input.height != null) obj.height = input.height;
  if (input.encodingFormat != null) obj.encodingFormat = input.encodingFormat;

  // Chapters -> schema.org Clip parts (hasPart). Cheap, and Google understands it.
  const chapters = chaptersFrom(input);
  if (chapters.length) {
    obj.hasPart = chapters.map((c) => ({
      "@type": "Clip",
      name: c.label,
      startOffset: c.start,
      endOffset: c.end,
    }));
  }

  const prov = resolveProvenance(input.provenance);
  if (prov) {
    obj.creator = { "@type": "SoftwareApplication", name: prov.generator, softwareVersion: prov.version };
    if (prov.digitalSourceType) {
      // schema.org has no native field; expose the IPTC term as a PropertyValue.
      obj.additionalProperty = [
        { "@type": "PropertyValue", propertyID: "IPTC:digitalSourceType", value: prov.digitalSourceType },
      ];
    }
  }
  return obj;
}

/** Convenience: the JSON-LD as a `<script type="application/ld+json">` string. */
export function toVideoObjectScript(input: VideoMetaInput): string {
  const json = JSON.stringify(toVideoObject(input));
  return `<script type="application/ld+json">${json}</script>`;
}

// ---------------------------------------------------------------------------
// IIIF Presentation 3.0 Manifest
// ---------------------------------------------------------------------------

// Build a IIIF Presentation API 3.0 Manifest for a single time-based Canvas.
// `input.id` is the manifest IRI (a placeholder is used if absent). Chapters
// (from sections) become `structures` Ranges targeting temporal fragments.
export function toIIIFManifest(input: VideoMetaInput): Record<string, any> {
  const duration = metaDuration(input);
  const lang = input.language;
  const base = (input.id || "https://example.org/ecmanim/manifest").replace(/\/+$/, "");
  const canvasId = `${base}/canvas/1`;
  const format = input.encodingFormat || "video/mp4";

  const body: Record<string, any> = {
    id: input.contentUrl || `${base}/media`,
    type: "Video",
    format,
  };
  if (duration > 0) body.duration = duration;
  if (input.width != null) body.width = input.width;
  if (input.height != null) body.height = input.height;

  const canvas: Record<string, any> = {
    id: canvasId,
    type: "Canvas",
  };
  if (duration > 0) canvas.duration = duration;
  if (input.width != null) canvas.width = input.width;
  if (input.height != null) canvas.height = input.height;
  canvas.items = [{
    id: `${canvasId}/page`,
    type: "AnnotationPage",
    items: [{
      id: `${canvasId}/annotation/1`,
      type: "Annotation",
      motivation: "painting",
      body,
      target: canvasId,
    }],
  }];

  const manifest: Record<string, any> = {
    "@context": "http://iiif.io/api/presentation/3/context.json",
    id: `${base}/manifest.json`,
    type: "Manifest",
  };
  const label = langMap(input.name ?? "Untitled", lang);
  if (label) manifest.label = label;
  const summary = langMap(input.description, lang);
  if (summary) manifest.summary = summary;
  manifest.items = [canvas];

  const chapters = chaptersFrom(input);
  if (chapters.length) {
    manifest.structures = chapters.map((c, i) => ({
      id: `${base}/range/${i + 1}`,
      type: "Range",
      label: langMap(c.label, lang),
      items: [{ id: `${canvasId}#t=${trim(c.start)},${trim(c.end)}`, type: "Canvas" }],
    }));
  }

  const prov = resolveProvenance(input.provenance);
  if (prov) {
    manifest.metadata = [
      { label: langMap("Generator", lang), value: langMap(`${prov.generator} ${prov.version}`, lang) },
    ];
    if (prov.sceneName) {
      manifest.metadata.push({ label: langMap("Scene", lang), value: langMap(prov.sceneName, lang) });
    }
    if (prov.digitalSourceType) {
      manifest.metadata.push({ label: langMap("Digital Source Type", lang), value: langMap(prov.digitalSourceType, lang) });
    }
  }
  if (input.thumbnailUrl != null) {
    const thumbs = Array.isArray(input.thumbnailUrl) ? input.thumbnailUrl : [input.thumbnailUrl];
    manifest.thumbnail = thumbs.map((u) => ({ id: u, type: "Image" }));
  }
  return manifest;
}

// Format a number for a temporal fragment (drop trailing zeros).
function trim(n: number): string {
  return Number.isInteger(n) ? String(n) : String(Number(n.toFixed(3)));
}

// ---------------------------------------------------------------------------
// IIIF ingest (the one importer)
// ---------------------------------------------------------------------------

export interface ResolvedIIIFVideo {
  url: string;
  format?: string;
  width?: number;
  height?: number;
  duration?: number;
  chapters: Chapter[];
}

// Parse a IIIF Presentation 3.0 Manifest (already-fetched object) into the video
// body URL + geometry + chapters, for VideoMobject ingestion. Tolerant of the
// common shapes (body as an object, an array, or a Choice with `items`).
export function resolveIIIFVideo(manifest: any): ResolvedIIIFVideo {
  if (!manifest || typeof manifest !== "object") {
    throw new Error("resolveIIIFVideo: not a IIIF manifest object");
  }
  const canvas = (manifest.items || []).find((c: any) => c?.type === "Canvas") ?? manifest.items?.[0];
  if (!canvas) throw new Error("resolveIIIFVideo: manifest has no Canvas");

  // Find the painting annotation's video body.
  let body: any = null;
  for (const page of canvas.items || []) {
    for (const anno of page.items || []) {
      if (anno?.motivation && anno.motivation !== "painting") continue;
      body = anno?.body;
      if (body) break;
    }
    if (body) break;
  }
  // Body may be an array or a Choice ({ items: [...] }); pick the first Video/Sound.
  const candidates: any[] = Array.isArray(body) ? body : body?.items ? body.items : [body];
  const video = candidates.find((b) => b && (b.type === "Video" || /^video\//.test(b.format || ""))) ?? candidates[0];
  if (!video || !video.id) throw new Error("resolveIIIFVideo: no video body found in the Canvas");

  const chapters: Chapter[] = [];
  for (const range of manifest.structures || []) {
    if (range?.type !== "Range") continue;
    const label = firstLangValue(range.label) ?? "chapter";
    const target = (range.items || []).find((it: any) => typeof it?.id === "string" && it.id.includes("#t="));
    const frag = target && /#t=([\d.]+),([\d.]+)/.exec(target.id);
    if (frag) chapters.push({ label, start: Number(frag[1]), end: Number(frag[2]) });
  }

  return {
    url: video.id,
    format: video.format,
    width: numOrUndef(video.width ?? canvas.width),
    height: numOrUndef(video.height ?? canvas.height),
    duration: numOrUndef(video.duration ?? canvas.duration),
    chapters,
  };
}

/** True if `x` looks like a IIIF manifest object (for loadVideo auto-detect). */
export function isIIIFManifest(x: any): boolean {
  return !!x && typeof x === "object" &&
    (x.type === "Manifest" || (typeof x["@context"] === "string" && x["@context"].includes("iiif.io")) ||
     (Array.isArray(x["@context"]) && x["@context"].some((c: any) => typeof c === "string" && c.includes("iiif.io"))));
}

function firstLangValue(map: any): string | undefined {
  if (!map || typeof map !== "object") return undefined;
  for (const k of Object.keys(map)) {
    const v = map[k];
    if (Array.isArray(v) && v.length) return String(v[0]);
  }
  return undefined;
}

function numOrUndef(n: any): number | undefined {
  const v = Number(n);
  return Number.isFinite(v) ? v : undefined;
}
